### PR TITLE
Add ability to specify location of SAB Application toolbar

### PR DESCRIPTION
**Pull request by bodrick**
I have added the ability to specify the location of the SAB application toolbar to either appear at the top of the screen or bottom.  I also made some tweaks to the libraries used and eliminated the use of Ionic.Zip library using the native .NET 4.5 Compression libraries.

### CODE REVIEW

**Comment by danschlet** [comment]
Thank you for your contribution. We will review it and comment if there are problems. In general, we will discuss if we want to accept the option for the **SEB Taskbar** to be placed on top. As I commented in a reply to a post (don't know if the question was from you), we plan to integrate a side drawer (left slider) menu as an alternative UI for the options currently placed in the taskbar, for example when using one instance of SEB on a physical machine and one instance inside a virtual desktop. This will be a) consistent with the UI of the iOS version of SEB and b) not confusing for users. 

I don't like the idea at all to have one taskbar on top and one on bottom of the screen, this is very confusing for users. I actually think it's even better to have two SEB taskbars at the bottom in the meantime before we implement the side drawer menu.

**Comment by bodrick** [comment]
So just to add some clarification to my intent.  The toolbar on the top seems to be more inline with what our current users are more familiar with since it goes in line with other browsers with toolbars being on the top.  We had originally tried with the toolbar on the bottom but it caused confusion with the users.  Anyway just wanted to share my 2 cents :-)

**Comment by danschlet** [comment]
**SEB has a toolbar on the top**, enable it with [the option](https://www.safeexambrowser.org/windows/win_usermanual_en.html#AppearancePane) 
Enable browser window toolbar: Indicates if a toolbar is displayed on top of the browser window, with back/forward buttons (if navigation is enabled) and a reload button.

**The bar at the bottom is a TASKBAR, [see the Wikipedia definition](https://en.wikipedia.org/wiki/Taskbar).**  

SEB's user interface very much follows standards familiar to users:

- Web browser have a toolbar on top of each browser window, which displays back/forward navigation buttons, a page reload button and a URL/search field (which SEB doesn't provide for obvious reasons).
- Operating systems display a taskbar usually at the bottom of the screen (in macOS and iOS it's called Dock and can be configured to be at the left or right edge of the screen). The taskbar usually fills the full width of the screen, not only the width of a browser window like the toolbar. 
The taskbar displays running applications or icons for starting applications and on the right icons of widgets to change some system settings. 

If you would switch on the browser window toolbar (available in SEB for Windows since version 2.2) and in case you would be using permitted applications or additional resources, then I'm sure also your users would understand the difference between those two bars, because SEB is really consistent with common UI like in Windows. The SEB taskbar intentionally doesn't look identical to the one of Windows and has a simplified design, as the exam environment should be as clean and easy to use as possible.

Using the correct terminology is very important in cases like this, to avoid misunderstandings...

**Comment by bodrick** [comment]
Ah ok that makes a lot more sense, I see where my confusion was.  My apologies for getting this muddled.

**Comment by bodrick** [comment]
So with that clarified, it still seems valid to have the taskbar at the top or bottom (since this is certainly configurable in windows).
For the browser toolbar configuration, what functionality currently exists, obviously forward/back and refresh etc.

**Comment by bodrick** [comment]
So I just added some more commits to improve the wix installer, as well as some missing files from pdfjs caused by gitignore.

**Pull request closed without merging**
